apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
    spec:

      containers:
        - name: dispatcher-service
          image: mhacioglu/dispatcher-service:0.0.2-SNAPSHOT
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:  [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9003
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://polar-config:8888
            - name: SPRING_RABBITMQ_HOST
              value: polar-rabbitmq